byoa.html: byoa.md template.html kanban.js spotsocket.js prompt.js slinky.js
	pandoc -f markdown+hard_line_breaks-implicit_figures byoa.md -o byoa.html --template=template.html --highlight-style=pygments --wrap=none --shift-heading-level-by=1
